### ISSUE TITLE
TypeError: Cannot set property 'fullCalendar' of undefined

### ISSUE THREAD

**Issue by AndrewKralovec** [nekken/ng2-fullcalendar#25]
So I'm trying to use this module however, when i start my application i get the following error. 
```
System.Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot set property 'fullCalendar' of undefined
    at c:\Users\andrew\Documents\Visual Studio 2015\Projects\Angular2Application1\Angular2Application1\node_modules\fullcalendar\dist\fullcalendar.js:31:19
    at $.fullCalendar.version (c:\Users\andrew\Documents\Visual Studio 2015\Projects\Angular2Application1\Angular2Application1\node_modules\fullcalendar\dist\fullcalendar.js:12:20)
    at Object.<anonymous> (c:\Users\andrew\Documents\Visual Studio 2015\Projects\Angular2Application1\Angular2Application1\node_modules\fullcalendar\dist\fullcalendar.js:17:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

I think im getting this issue because im trying to pre-render all my angular2 stuff on the server, and for some reason node.js doesn't recognize this module. 

Any ideas on how to fix this issue ? 

Components/Typescript 
```
import { Component, } from '@angular/core';

@Component({
    selector: 'home',
    template: require('./home.component.html'),
    styles: [require('./home.component.css')]
})
export class HomeComponent {
    viewDate: Date = new Date();
    events = [];
    calendarOptions = null; 
    constructor() {
        console.log("Test");
        this.calendarOptions = {
        height: 'parent',
        fixedWeekCount : false,
        defaultDate: '2016-09-12',
        editable: true,
        eventLimit: true, // allow "more" link when too many events
        events: [
          {
            title: 'All Day Event',
            start: '2016-09-01'
          },
          {
            title: 'Long Event',
            start: '2016-09-07',
            end: '2016-09-10'
          },
          {
            id: 999,
            title: 'Repeating Event',
            start: '2016-09-09T16:00:00'
          },
          {
            id: 999,
            title: 'Repeating Event',
            start: '2016-09-16T16:00:00'
          },
          {
            title: 'Conference',
            start: '2016-09-11',
            end: '2016-09-13'
          },
          {
            title: 'Meeting',
            start: '2016-09-12T10:30:00',
            end: '2016-09-12T12:30:00'
          },
          {
            title: 'Lunch',
            start: '2016-09-12T12:00:00'
          },
          {
            title: 'Meeting',
            start: '2016-09-12T14:30:00'
          },
          {
            title: 'Happy Hour',
            start: '2016-09-12T17:30:00'
          },
          {
            title: 'Dinner',
            start: '2016-09-12T20:00:00'
          },
          {
            title: 'Birthday Party',
            start: '2016-09-13T07:00:00'
          },
          {
            title: 'Click for Google',
            url: 'http://google.com/',
            start: '2016-09-28'
          }
        ]
      };
    }
}
```
```
<div ng-if="calendarOptions">
    <angular2-fullcalendar [options]="calendarOptions"></angular2-fullcalendar>
</div>
```

**Comment by mkornilu** [comment]
did you solve this?

**Comment by cristiancpl** [comment]
+1

**Comment by ScottAgirs** [comment]
same thing in React
