### ISSUE TITLE
Error: Please add a @Pipe/@Directive/@Component annotation

### ISSUE THREAD

**Issue by sparrowonfire** [nekken/ng2-fullcalendar#40]
Hi,

I just installed this component in my project and i have followed the installation instructions as specified on the main page.

I can compile my app without errors however when i try to access it in the browser i get this error

> Uncaught Error: Unexpected value 'CalendarComponent' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:120246:34)
    at http://localhost:4200/vendor.bundle.js:133248:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:133230:54)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:144336:66)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:144295:52)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:144257:23)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5022:25)
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5008:21)
    at Object.541 (http://localhost:4200/main.bundle.js:315:124)

Does anyone know what could be causing this?

Thanks in advance!

**Comment by nikopolv** [comment]
I get the same.

e: I use ng-cli with angular2

**Comment by KrisBraun** [comment]
I got the same error. I don't think this package is using the correct approach by including the component directly rather than importing a module, because it's pulling in a separate dependancy on a specific version of Angular. This package uses proper module imports and works for me: https://github.com/lbertenasco/ap-ng2-fullcalendar

**Comment by Abhay2012** [comment]
I'm also getting the same error, did you get any solution??

**Comment by cristiancpl** [comment]
+1

**Comment by abrahamsankutty** [comment]
https://github.com/lbertenasco/ap-ng2-fullcalendar use this for angular cli

**Comment by mganigapeta** [comment]
I am also getting same error any solutions for this....?
