### ISSUE TITLE
compilation errors with angular 6

### ISSUE THREAD

**Issue by gsiradze** [nekken/ng2-fullcalendar#71]
I'm getting this error when including CalendarComponent inside my module

```
ERROR in ./node_modules/angular2-fullcalendar/src/calendar/calendar.ts
Module build failed: Error: C:\Users\...\node_modules\angular2-fullcalendar\src\calendar\calendar.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\...\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\...\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by FurtunaDaniel** [comment]
Same issue here
